site_name: Homelab de Marcos
site_url: https://TUUSUARIO.github.io/homelab-docs/

theme:
  name: lux

extra_css:
  - css/extra.css

plugins:
  - search
  - mermaid2
  - panzoom:
      key: none
      hint_location: bottom
      full_screen: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

nav:
  - Inicio: index.md
  - Arquitectura: architecture.md
  - Direccionamiento: addressing-plan.md
  - Fases:
      - Fase 1 - Configuración inicial: phases/01-initial-setup.md
  - Incidentes:
      - 001 - Conflicto de virtualización entre VMware y Windows: incidents/001-vmware-windows-virtualization-conflict.md