languageCode = "es"
languageName = "Español"
weight = 1
title = "Laboratorio de Redes"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/HomeLab.png"
  description = "Manteniendo la Matrix..."

[params.author]
  name = "Marcos Sánchez"
  email = "marcospersonalmail@gmail.com"
  image = "img/HomeLab.png"
  headline = "Manteniendo la Matrix..."
  bio = "Soy el administrador. Claro que puedo!"
  links = [
    { github = "https://github.com/Marcos-SA-git" }
  ]
