# -- Menú Principal --
# El menú principal se muestra en el encabezado en la parte superior de la página.

[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Arquitectura"
  pageRef = "arch"
  weight = 20

[[main]]
  name = "Fases"
  pageRef = "phases"
  weight = 30

[[main]]
  name = "Incidencias"
  pageRef = "incidents"
  weight = 40

[[main]]
  name = "Toma de decisiones"
  pageRef = "adr"
  weight = 50

# [[main]]
#   name = "Ejemplos"
#   weight = 20
# 
# [[main]]
#   name = "Recetas"
#   parent = "Ejemplos"
#   pageRef = "guides"
#   weight = 40


[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Marcos-SA-git/"
  weight = 400


# [[subnavigation]]
#   name = "An interesting topic"
#   pageRef = "tags/interesting-topic"
#   weight = 50
# 
# [[subnavigation]]
#   name = "My Awesome Category"
#   pageRef = "categories/awesome"
#   weight = 20


# -- Menú de Pie de Página --

 [[footer]]
   name = "Etiquetas"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categorías"
   pageRef = "categories"
   weight = 20
